- name: rabbitmq-restart
  service: >
    name={{ service_rabbitmq }}
    state=restarted

- name: rabbitmq-start
  service: >
    name={{ service_rabbitmq }}
    state=started

- name: rabbitmq-stop
  service: >
    name={{ service_rabbitmq }}
    state=stopped
